### ISSUE TITLE
Opdatér beskrivelse i README

### ISSUE THREAD

**Issue by kalkun** [kalkun/finansloven#6]

**Comment by dzgreen** [comment]
Hej igen. Tænker du på mere end bare at slette linket og ændre årstallene? Hvad siger du til at jeg sætter hosting af data-browseren op på fx Netlify?

**Comment by kalkun** [comment]
@dzgreen jeg har sat hosting til via github pages, så det burde ikke være et problem for fremtiden :) 

https://kalkun.github.io/finansloven/public/
